/// Flutter icons InsightTimerIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InsightTimerIcons
///      fonts:
///       - asset: fonts/InsightTimerIcons.ttf
///
/// 
///
import 'package:flutter_web/widgets.dart';

class InsightTimerIcons {
  InsightTimerIcons._();

  static const _kFontFam = 'InsightTimerIcons';

  static const IconData reminder = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData privacy = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData arrow_right_thin = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData hundred = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData listen_privately_checked = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData listen_privately_unchecked = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData course = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData community = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData music = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData guided = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData timer = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData inbox = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData library_icon = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData today = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData playlist = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData my_profile = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData daily = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData collection = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData local = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData right_arrow = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData btn_back = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData sleep = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData bookmark_selected = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData bookmark_unselected = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData arrow_left = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData cloud_hollow = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData bird = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData beginner = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData kid = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData heart_unchecked = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData dot_3 = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData add_circle = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData events_1 = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData volume_up = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData head_phone = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData activity = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData done = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData close_modal_arrow = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData live = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData cloud_downloaded = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData forward = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData rewind = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData list = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData night_mode = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData support = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData events = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData podcasts = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData down_arrow = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData circle = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData comment_unchecked = const IconData(0xf0e5, fontFamily: _kFontFam);
}
